spring.application.name=flexbuy

# postgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/flexbuy
spring.datasource.username=flex
spring.datasource.password=321flex
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080

# env
jwt.privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCC5PmwE/0ZF5iCwM4Yq4wYVq6brs4zJ5WhzuPwySm+stg==
jwt.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIRO2S+Xk7gSeEnFav82otzQVyyFaKl/g8k4IFVd6nq7TghygkxcXCgt20xwpkMO6DcTTAaDxZ7qBYpUVjHfw6Q==
jwt.expiration = 86400000


# reset Passwords
reset.token=beb49373100ba8af1e68009061eadd9b6e2d9a94c90f846908f0cdd2df24b7d4f658d3b5

# spring mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your email
spring.mail.password=your email password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
